// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kolbatilixzwubxqhgaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvbGJhdGlsaXh6d3VieHFoZ2F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjI1NTgsImV4cCI6MjA2OTM5ODU1OH0.gGUw5NY_eqE73DAs0i1yIycWqatoo6AYzr1Mg7mSIgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});